# Delete all generated files
rm -f *.docx *.htm *.pdf diss.md

# Delete the generated folder for the runtex stuff
./latexrun --clean-all
rm -rf latex.out

# Delete autogenerated figures
rm -f figures/testfigure.png