#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -e

pdflatex Bewertungskriterien
biber Bewertungskriterien
pdflatex Bewertungskriterien

pdflatex Präsentation
biber Präsentation
pdflatex Präsentation

pdflatex Aufgabe
biber Aufgabe
pdflatex Aufgabe

git add Aufgabe.pdf Bewertungskriterien.pdf Präsentation.pdf