#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -e

pdflatex -halt-on-error -interaction=nonstopmode Bewertungskriterien
biber Bewertungskriterien
pdflatex -halt-on-error -interaction=nonstopmode Bewertungskriterien

pdflatex -halt-on-error -interaction=nonstopmode Präsentation
biber Präsentation
pdflatex -halt-on-error -interaction=nonstopmode Präsentation

pdflatex -halt-on-error -interaction=nonstopmode Aufgabe
biber Aufgabe
pdflatex -halt-on-error -interaction=nonstopmode Aufgabe

git add Aufgabe.pdf Bewertungskriterien.pdf Präsentation.pdf